### ISSUE TITLE
[FEATURE] 스트리밍 서비스 API 구현

### ISSUE THREAD

**Issue by lgsok00** [lgsok00/settlement-system#6]
### Description
---
스트리밍 서비스 관련 API 구현

### Todo
---
- [x] 동영상 재생 API
- [x] 동영상 중지 API
- [x] 동영상 시청 기록 관리
- [x] 광고 시청 기록 관리

### ETC
---
기타 사항
